services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
    env_file:
      - .env
    volumes:
      - ./apps/backend/Cvfiles:/app/dist/Cvfiles
    depends_on:
      chromadb:
        condition: service_healthy
    networks:
      - back-tier
    command: pnpm start:dev

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - CHROMA_SERVER_DB=duckdb
    healthcheck:
      test:
        ["CMD", "/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/8000"]
      interval: 30s
      timeout: 15s
      retries: 50
      start_period: 300s
    networks:
      - back-tier

volumes:
  chromadb_data:
    driver: local

networks:
  back-tier:
    driver: bridge
