# Development Dockerfile
FROM node:18
WORKDIR /app

# Install PNPM
RUN npm install -g pnpm

# sharp
RUN npm install -g pnpm
RUN apt-get update && apt-get install -y libvips-dev \
    build-essential \
    libvips-dev \
    libjpeg-dev \
    libpng-dev \
    libwebp-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pnpm add sharp
# Copy package files and install dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --force

# Copy source code and config
COPY tsconfig.json ./
COPY src ./src

# Expose port
EXPOSE 3003

# Run in development mode with hot-reloading
CMD ["pnpm", "start:dev"]